//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flight_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees_Phone
    {
        public string ssn { get; set; }
        public int Phone { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
