//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flight_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flights
    {
        public string flightnumber { get; set; }
        public int companynumber { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime time { get; set; }
        public string home { get; set; }
        public string away { get; set; }
        public int plannumber { get; set; }
    
        public virtual Companies Companies { get; set; }
    }
}
