//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flight_System.Models
{
    using System;
    using System.Collections;
    using System.Collections.Generic;

    public partial class Plans
    {
        public string ssn_employee_last { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public int planId { get; set; }
        public int chair { get; set; }
        public int companynumber { get; set; }
    
        public virtual Companies Companies { get; set; }
        public virtual Employees Employees { get; set; }
        public string ssn_employee_first { get;  set; }
        public string ssn_employee { get;  set; }
    }
    
}
